services:
  - type: web
    name: sermon-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20
      - fromGroup: sermon-processing-env

envVarGroups:
  - name: sermon-processing-env
    envVars:
      - key: REDIS_URL
        value: ""
      - key: REPLICATE_API_TOKEN
        value: ""
      - key: CLOUDFLARE_R2_ENDPOINT_URL
        value: ""
      - key: CLOUDFLARE_R2_ACCESS_KEY_ID
        value: ""
      - key: CLOUDFLARE_R2_SECRET_ACCESS_KEY
        value: ""
      - key: CLOUDFLARE_R2_BUCKET_NAME
        value: ""



